/**
 * 首页欢迎语 - 每次进入首页随机显示一条
 */
export const HOME_GREETINGS = [
  "Ready to learn Chinese?",
  "Let's dive into Chinese!",
  "Your Chinese journey starts here.",
  "Time to practice!",
  "Chinese made easy.",
  "Let's get started!",
  "Start your day with Chinese.",
  "Keep the momentum going!",
  "Every character counts.",
  "One word at a time.",
  "Learning Chinese, one step at a time.",
  "Your daily dose of Chinese.",
  "Practice makes perfect.",
  "Let's make progress today.",
  "Ready when you are!",
  "Chinese awaits!",
  "Unlock a new language.",
  "Discover the beauty of Chinese.",
  "Let's build your vocabulary.",
  "Small steps, big results.",
  "Today's the day!",
  "Ready to expand your mind?",
  "Let's crack the code.",
  "Chinese is calling.",
  "Your next word is waiting.",
  "Stay curious, keep learning.",
  "Let's level up your Chinese.",
  "Every session counts.",
  "Ready for a challenge?",
  "Let's make it fun!",
  "Your brain will thank you.",
  "New words, new possibilities.",
  "Let's keep the streak alive!",
  "Consistency is key.",
  "You've got this!",
  "Let's add more words today.",
  "Progress over perfection.",
  "Ready to impress yourself?",
  "Chinese is easier than you think.",
  "Let's unlock another character.",
  "Your vocabulary is growing.",
  "Learning never gets old.",
  "Let's keep the ball rolling.",
  "One more word, one more win.",
  "Ready to surprise yourself?",
  "Let's make today count.",
  "Your future self will thank you.",
  "Small wins, big confidence.",
  "Let's keep the fire burning.",
  "Chinese is within reach.",
  "Ready to stretch your brain?",
  "Let's turn effort into progress.",
  "Every word opens a door.",
  "You're one session away from progress.",
  "Let's keep the habit strong.",
  "Learning is a superpower.",
  "Ready to add another word?",
  "Let's make Chinese feel familiar.",
  "Your dedication shows.",
  "One character closer to fluency.",
  "Let's keep the rhythm going.",
  "Ready to learn something new?",
  "Chinese gets easier with practice.",
  "Let's build on what you know.",
  "You're doing great!",
  "Let's keep the streak going.",
  "Ready to level up?",
  "Every minute of practice matters.",
  "Let's make Chinese stick.",
  "Your progress is real.",
  "Ready to add to your collection?",
  "Let's keep the momentum.",
  "Chinese is waiting for you.",
  "One session can change everything.",
  "Let's make today productive.",
  "Ready to feel accomplished?",
  "Learning is the best investment.",
  "Let's keep growing.",
  "Your brain loves new words.",
  "Ready to surprise yourself today?",
  "Let's make Chinese feel natural.",
  "Every word is a victory.",
  "Let's keep the habit alive.",
  "Ready to expand your world?",
  "Chinese opens doors.",
  "Let's make progress feel easy.",
  "You're building something great.",
  "Let's add another brick today.",
  "Ready to feel proud?",
  "Learning never stops.",
  "Let's keep the curiosity alive.",
  "Your future is multilingual.",
  "Ready to take the next step?",
  "Let's make Chinese yours.",
  "Every session builds confidence.",
  "Let's keep the energy up.",
  "Ready to learn something cool?",
  "Chinese is full of surprises.",
  "Let's make today memorable.",
  "You're closer than you think.",
  "Let's keep the progress flowing.",
  "Ready to add another skill?",
  "Learning is a gift to yourself.",
  "Let's make Chinese click.",
  "Your journey continues here.",
  "Let's keep the passion alive.",
  "Ready to unlock more?",
  "Chinese gets better with you.",
  "Let's make today count.",
  "Every word brings you closer.",
  "Let's keep the learning fun.",
  "Ready to feel the progress?",
  "Your vocabulary is your superpower.",
  "Let's make Chinese feel like home.",
  "One more session, one more win.",
  "Let's keep the excitement going.",
  "Ready to add another layer?",
  "Chinese is a journey, not a race.",
  "Let's make today productive.",
  "You're building fluency every day.",
  "Let's keep the habit strong.",
  "Ready to discover more?",
  "Learning Chinese opens new worlds.",
  "Let's make progress visible.",
  "Your effort is paying off.",
  "Let's keep the streak alive!",
];

export function getRandomGreeting() {
  return HOME_GREETINGS[Math.floor(Math.random() * HOME_GREETINGS.length)];
}
